# Original script from https://github.com/silx-kit/silx

sudo: required

language: python

notifications:
  email: false

env:
  global:
  - CACHED_FOLDER=$HOME/cached
  - BUILD_FOLDER=$HOME/build

matrix:
  include:
    - python: 2.7
      os: linux

    - python: 3.4
      os: linux

    - python: 3.5
      os: linux

    - python: 3.6
      os: linux

cache:
  directories:
  - $HOME/.cache/pip
  - $CACHED_FOLDER

before_install:
  - mkdir -p $CACHED_FOLDER
  - mkdir -p $BUILD_FOLDER

install:
  # Install Travis specific dependencies
  - cd $BUILD_FOLDER
  - if [ ${TRAVIS_OS_NAME:-'linux'} = 'linux' ]; then . $TRAVIS_BUILD_DIR/ci/prepare_travis-linux.sh; fi

  # Install general build dependencies
  - cd $BUILD_FOLDER
  - if [ ${TRAVIS_OS_NAME:-'linux'} = 'linux' ]; then . $TRAVIS_BUILD_DIR/tools/prepare_install-linux.sh -y -u; fi

  # Package directory  
  - cd $TRAVIS_BUILD_DIR

  # Print Python info
  - $PYTHOBIN ci/info_platform.py
  - $PIPBIN list

  # Build package
  - $PYTHOBIN setup.py build
  - $PYTHOBIN setup.py sdist bdist_wheel
  - ls dist

  # Install package
  - PROJECTNAME=`python setup.py name|tail -1`
  - $PIPBIN install --pre --no-index --find-links=dist/ ${PROJECTNAME}

script:
  # Test the installed package
  - cd $HOME
  - $PYTHOBIN -m $PROJECTNAME.tests.test_all

