# Original script from https://github.com/silx-kit/pyFAI

version: "{build}"
shallow_clone: true
build: false

os:
    - Visual Studio 2015

cache:
    - '%LOCALAPPDATA%\pip\Cache'
    - '%CACHED_FOLDER%'

environment:
    global:
        WIN_SDK_ROOT: "C:\\Program Files\\Microsoft SDKs\\Windows"
        VENV_NAME: "venv_build"
        CACHED_FOLDER: "%HOMEDRIVE%%HOMEPATH%\\cashed"
        BUILD_FOLDER: "%HOMEDRIVE%%HOMEPATH%\\build"

    matrix:
        - PYTHON_DIR: "C:\\Python27"
        - PYTHON_DIR: "C:\\Python27-x64"
        - PYTHON_DIR: "C:\\Python34"
        - PYTHON_DIR: "C:\\Python34-x64"
        - PYTHON_DIR: "C:\\Python35"
        - PYTHON_DIR: "C:\\Python35-x64"
        - PYTHON_DIR: "C:\\Python36"
        - PYTHON_DIR: "C:\\Python36-x64"

init:

    # Before clone
    - ps: |
          [Environment]::SetEnvironmentVariable("path", "$PYTHON_DIR;$PYTHON_DIR\\Scripts;$env:path", "process")
    - ps: mkdir -force $env:CACHED_FOLDER
    - ps: mkdir -force $env:BUILD_FOLDER
    - ps: |
          Write-Host "Build worker environment variables:" -ForegroundColor Magenta
          Get-ChildItem Env: | %{"{0}={1}" -f $_.Name,$_.Value}

install:

    # Install Appveyor specific dependencies
    - ps: cd $env:BUILD_FOLDER
    - ps: invoke-expression "$env:APPVEYOR_BUILD_FOLDER\ci\prepare_appveyor-windows.ps1"

    # Install build dependencies
    - ps: cd $env:BUILD_FOLDER
    - ps: invoke-expression "$env:APPVEYOR_BUILD_FOLDER\tools\prepare_install-windows.ps1 -y -u"
    - ps: invoke-expression "$PIPBIN install --upgrade -r $env:APPVEYOR_BUILD_FOLDER/requirements-dev.txt"

build_script:

    # Package directory  
    - ps: $env:APPVEYOR_BUILD_FOLDER

    # Print Python info
    - ps: ls 
    - ps: invoke-expression "$PYTHONBIN ci\\info_platform.py"
    - ps: invoke-expression "$PIPBIN list"

    # Build package
    - ps: invoke-expression "$PYTHONBIN setup.py build"
    - ps: invoke-expression "$PYTHONBIN setup.py bdist_wheel bdist_msi"
    - ps: ls dist

    # Install package
    - ps: invoke-expression "$PIPBIN install --pre --no-index --find-links=dist/ $env:APPVEYOR_PROJECT_NAME"

test_script:

    # Test installation
    - ps: cd $env:HOMEDRIVE$env:HOMEPATH
    - ps: invoke-expression "$PYTHONBIN -m $env:APPVEYOR_PROJECT_NAME.tests.test_all"
    - ps: cd $env:APPVEYOR_BUILD_FOLDER

artifacts:
    # Archive the generated wheel package in the ci.appveyor.com build report.
    - path: dist\*
