# Original script from https://github.com/silx-kit/pyFAI

version: "{build}"
shallow_clone: true
build: false

os:
    - Visual Studio 2015

cache:
    - '%LOCALAPPDATA%\pip\Cache'
    - '%CACHED_FOLDER%'

environment:
    global:
        WIN_SDK_ROOT: "C:\\Program Files\\Microsoft SDKs\\Windows"
        VENV_NAME: "venv_build"
        CACHED_FOLDER: "%HOMEDRIVE%%HOMEPATH%\\cashed"
        BUILD_FOLDER: "%HOMEDRIVE%%HOMEPATH%\\build"

    matrix:
        - PYTHON: "C:\\Python27"
        - PYTHON: "C:\\Python27-x64"
        - PYTHON: "C:\\Python34"
        - PYTHON: "C:\\Python34-x64"
        - PYTHON: "C:\\Python35"
        - PYTHON: "C:\\Python35-x64"
        - PYTHON: "C:\\Python36"
        - PYTHON: "C:\\Python36-x64"

# Before clone
init:
    - ps: |
          Write-Host "Build worker environment variables:" -ForegroundColor Magenta
          Get-ChildItem Env: | %{"{0}={1}" -f $_.Name,$_.Value}
    - cmd: SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
    - cmd: mkdir -p %CACHED_FOLDER%
    - cmd: mkdir -p %BUILD_FOLDER%

install:

    # Install Appveyor specific dependencies
    - cmd: cd %BUILD_FOLDER%
    - ps: .\$APPVEYOR_BUILD_FOLDER\ci\prepare_appveyor-windows.ps1

    # Install build dependencies
    - cmd: cd %BUILD_FOLDER%
    - ps: $APPVEYOR_BUILD_FOLDER/tools/prepare_install-windows.ps1 -y -u
    - cmd: $PIPBIN install --upgrade -r %APPVEYOR_BUILD_FOLDER%/requirements-dev.txt

build_script:

    # Package directory  
    - cmd: cd %APPVEYOR_BUILD_FOLDER%

    # Print Python info
    - cmd: "%PYTHONBIN% ci\\info_platform.py"
    - cmd: "%PIPBIN% list"

    # Build package
    - cmd: "%PYTHONBIN% setup.py build"
    - cmd: "%PYTHONBIN% setup.py bdist_wheel bdist_msi"
    - ps: ls dist

    # Install package
    - cmd: "%PIPBIN% install --pre --no-index --find-links=dist/ %APPVEYOR_PROJECT_NAME%"

test_script:

    # Test installation
    - cmd: cd %HOMEDRIVE%%HOMEPATH%
    - cmd: "%PYTHONBIN% -m %APPVEYOR_PROJECT_NAME%.tests.test_all"
    - cmd: cd %APPVEYOR_BUILD_FOLDER%

artifacts:
    # Archive the generated wheel package in the ci.appveyor.com build report.
    - path: dist\*
